// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UhsZ9290TqfMQwa0vr6YsgdmPCRMlBM',
    appId: '1:938664043953:web:010625fdd5cd0a8ebb4990',
    messagingSenderId: '938664043953',
    projectId: 'fir-auth-b4579',
    authDomain: 'fir-auth-b4579.firebaseapp.com',
    storageBucket: 'fir-auth-b4579.appspot.com',
    measurementId: 'G-TD22Y4KNLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODD7GzmuvPMInK8tvYKZLXgbVx52G6MM',
    appId: '1:938664043953:android:b9aac64693203be4bb4990',
    messagingSenderId: '938664043953',
    projectId: 'fir-auth-b4579',
    storageBucket: 'fir-auth-b4579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNlNBeXtrwQYujLiEjZCtIifVo3KyvGQg',
    appId: '1:938664043953:ios:f78280b9b0080e81bb4990',
    messagingSenderId: '938664043953',
    projectId: 'fir-auth-b4579',
    storageBucket: 'fir-auth-b4579.appspot.com',
    iosClientId:
        '938664043953-g6hqj9o3abenh1n5s55untlkpia8rhkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNlNBeXtrwQYujLiEjZCtIifVo3KyvGQg',
    appId: '1:938664043953:ios:f78280b9b0080e81bb4990',
    messagingSenderId: '938664043953',
    projectId: 'fir-auth-b4579',
    storageBucket: 'fir-auth-b4579.appspot.com',
    iosClientId:
        '938664043953-g6hqj9o3abenh1n5s55untlkpia8rhkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
